<!--        <a class=link3 href="upgrade.php"><font color=yellow>upgrade</font></a>
        <font class=empiretext>|</font>
-->       
        <a class=link3 href="/">home</a>
        <font class=empiretext>|</font>
        <a class=link3 href="account.php">account</a>
        <font class=empiretext>|</font>               
        <a class=link3 href="reminders.php">reminders</a>
        <font class=empiretext>|</font>
        <a class=link3 href="allowlist.php">allow list</a>       
        <font class=empiretext>|</font>
        <a class=link3 href="reminderhelp.php">help</a>       
        <font class=empiretext>|</font>
			<!--<a class=link3 href="http://forum.remindme.cc">forum</a>
        <font class=empiretext>|</font>-->
        <a class=link3 href="contact.php">contacts</a>
        <font class=empiretext>|</font>        
         <a class=link3 href="suggestions.php">suggestions</a>
        <font class=empiretext>|</font>
        <a class=link3 href="login.php?logout=true">logout</a>               