        <a class=link3 href="/">home</a>
        <font class=empiretext>|</font>
        <a class=link3 href="login.php">login</a>
        <font class=empiretext>|</font>
        <a class=link3 href="registerform.php">register</a>
        <font class=empiretext>|</font>
        <!--<a class=link3 href="upgrade.php">upgrade plans</a>
        <font class=empiretext>|</font>-->
        <!--<a class=link3 href="http://forum.remindme.cc">forum</a>
        <font class=empiretext>|</font>-->
        <a class=link3 href="reminderhelp.php">how it works</a> 
        <font class=empiretext>|</font>
        <a class=link3 href="contact.php">contacts</a>